const passwordBlacklist = (user) => {
  return [
    user.email.slice(0, 1).toUpperCase() + user.email.slice(1),
    user.email.slice(0, 1).toUpperCase() + user.email.slice(1) + "0",
    user.email.slice(0, 1).toUpperCase() + user.email.slice(1) + "1",
    user.email.slice(0, 1).toUpperCase() + user.email.slice(1) + "12",
    user.email.slice(0, 1).toUpperCase() + user.email.slice(1) + "123",
    user.email.slice(0, 1).toUpperCase() + user.email.slice(1) + "1234",
    user.email.slice(0, 1).toUpperCase() + user.email.slice(1) + "12345",
    user.fName.slice(0, 1).toUpperCase() + user.fName.slice(1) + "0",
    user.lName.slice(0, 1).toUpperCase() + user.lName.slice(1) + "0",
    user.fName.slice(0, 1).toUpperCase() + user.fName.slice(1) + "1",
    user.lName.slice(0, 1).toUpperCase() + user.lName.slice(1) + "1",
    user.fName.slice(0, 1).toUpperCase() + user.fName.slice(1) + "12",
    user.lName.slice(0, 1).toUpperCase() + user.lName.slice(1) + "12",
    user.fName.slice(0, 1).toUpperCase() + user.fName.slice(1) + "123",
    user.lName.slice(0, 1).toUpperCase() + user.lName.slice(1) + "123",
    user.fName.slice(0, 1).toUpperCase() + user.fName.slice(1) + "1234",
    user.lName.slice(0, 1).toUpperCase() + user.lName.slice(1) + "1234",
    user.fName.slice(0, 1).toUpperCase() + user.fName.slice(1) + "12345",
    user.lName.slice(0, 1).toUpperCase() + user.lName.slice(1) + "12345",
    user.fName.toLowerCase() + user.lName + "0",
    user.fName.toLowerCase() + user.lName + "1",
    user.fName.toLowerCase() + user.lName + "12",
    user.fName.toLowerCase() + user.lName + "123",
    user.fName.toLowerCase() + user.lName + "1234",
    user.fName.toLowerCase() + user.lName + "12345",
    user.fName + user.lName + "0",
    user.fName + user.lName + "1",
    user.fName + user.lName + "12",
    user.fName + user.lName + "123",
    user.fName + user.lName + "1234",
    user.fName + user.lName + "12345",
    user.fName + "0",
    user.lName + "0",
    user.fName + "1",
    user.lName + "1",
    user.fName + "12",
    user.lName + "12",
    user.fName + "123",
    user.lName + "123",
    user.fName + "1234",
    user.lName + "1234",
    user.fName + "12345",
    user.lName + "12345",
    "Senha123",
    "Senha1234",
    "Senha12345",
    "Minhasenha1",
    "Minhasenha12",
    "Minhasenha123",
    "Minhasenha1234",
    "Minhasenha12345",
    "MinhaSenha1",
    "MinhaSenha12",
    "MinhaSenha123",
    "MinhaSenha1234",
    "MinhaSenha12345",
    "Password1",
    "Password12",
    "Password123",
    "Password1234",
    "Password12345",
    "Passw0rd",
    "Passw0rd1",
    "Passw0rd12",
    "Passw0rd123",
    "Passw0rd1234",
    "Passw0rd12345",
  ];
};

module.exports = passwordBlacklist;
